# Site settings
title: Path to Programming
header-img: img/home-bg.png
email: spencerwgoodman@icloud.com
copyright_name: swgoodman
description: > # this means to ignore newlines until "baseurl:"
  My experience on the path to programming. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  swgoodman
learn_profile: swgoodman
email_username: spencerwgoodman@icloud.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
